--- ./project/MQOMv2.1/NEON_Implementation/mqom2_cat1_gf2_fast_r3/Makefile.backup	2026-05-31 16:05:05.745371334 +0200
+++ ./project/MQOMv2.1/NEON_Implementation/mqom2_cat1_gf2_fast_r3/Makefile	2026-06-01 19:17:56.658321602 +0200
@@ -1,3 +1,5 @@
+# Modified by Alexandre Stordeur
+
 # Compiler detection
 # Detect if we are using clang or gcc
 CLANG :=  $(shell $(CC) -v 2>&1 | grep clang)
@@ -37,7 +39,7 @@
 # Rinjdael related stuff
 RIJNDAEL_DIR = rijndael
 RIJNDAEL_INCLUDES = $(RIJNDAEL_DIR)
-RIJNDAEL_SRC_FILES = $(RIJNDAEL_DIR)/rijndael_ref.c $(RIJNDAEL_DIR)/rijndael_table.c $(RIJNDAEL_DIR)/rijndael_aes_ni.c $(RIJNDAEL_DIR)/rijndael_ct64.c
+RIJNDAEL_SRC_FILES = $(RIJNDAEL_DIR)/rijndael_ref.c $(RIJNDAEL_DIR)/rijndael_table.c $(RIJNDAEL_DIR)/rijndael_aes_ni.c $(RIJNDAEL_DIR)/rijndael_ct64.c $(RIJNDAEL_DIR)/rijndael_neon.c
 ifeq ($(RIJNDAEL_OPT_ARMV7M),1)
   # Force RIJNDAEL optimized assembly usage where possible
   CFLAGS += -DRIJNDAEL_OPT_ARMV7M
@@ -106,6 +108,11 @@
   # Constant time bitslice Rijndael
   CFLAGS += -DRIJNDAEL_BITSLICE
 endif
+ifeq ($(RIJNDAEL_NEON),1)
+  # Constant time bitslice Rijndael
+  CFLAGS += -DRIJNDAEL_NEON
+endif
+
 
 ifeq ($(FIELDS_REF),1)
   # Reference implementation for fields
@@ -119,6 +126,10 @@
   # Force AVX512 implementation for fields
   CFLAGS += -DFIELDS_AVX512
 endif
+ifeq ($(FIELDS_NEON),1)
+  # Force NEON implementation for fields
+  CFLAGS += -DFIELDS_NEON
+endif
 ifeq ($(USE_GF256_TABLE_MULT),1)
   # Use non-constant time GF(256) 65 kB table (in flash/ROM) multiplication
   CFLAGS += -DUSE_GF256_TABLE_MULT
@@ -231,6 +242,15 @@
   CFLAGS := $(subst -mtune=native,,$(CFLAGS))
   CFLAGS += -maes -mgfni -mavx512bw -mavx512f -mavx512vl -mavx512vpopcntdq -mavx512vbmi
 endif
+ifeq ($(FORCE_PLATFORM_NEON),1)
+  CFLAGS := $(subst -march=native,,$(CFLAGS))
+  CFLAGS := $(subst -mtune=native,,$(CFLAGS))
+
+  # ARMv7+-A + NEON
+  # TODO à voir si on garde
+  CFLAGS += -DFIELDS_NEON -DRIJNDAEL_NEON
+endif
+
 
 ## Togles for various analysis and other useful stuff
 # Static analysis of gcc
@@ -288,6 +308,11 @@
     ifneq ($(KECCAK_DETECT_PLATFORM_AVX2),)
       KECCAK_PLATFORM=avx2
     else
+    # Detect ARM NEON / AArch64
+    KECCAK_DETECT_PLATFORM_NEON=$(shell $(CC) $(CFLAGS) $(EXTRA_CFLAGS) -dM -E - < /dev/null 2> /dev/null |egrep -e __ARM_NEON__ -e __ARM_NEON -e __aarch64__)
+    ifneq ($(KECCAK_DETECT_PLATFORM_NEON),)
+      KECCAK_PLATFORM=neon
+    else
       # Possibly detect ARMv7M to use the assembly optimized version
       KECCAK_DETECT_PLATFORM_ARMV7M=$(shell $(CC) $(CFLAGS) $(EXTRA_CFLAGS) -dM -E - < /dev/null 2> /dev/null |egrep -e __ARM_ARCH_7M__ -e __ARM_ARCH_7EM__)
       ifneq ($(KECCAK_DETECT_PLATFORM_ARMV7M),)
